### PR TITLE
add cervical cancer external parameter validation scripts

### PR DESCRIPTION
**Pull request by yongqx**

### CODE REVIEW

**Review by aflaxman — APPROVED** [review]

**Comment by mattkappel** [comment]
Is there a reason the cervical cancer validation scripts aren't going in the cervical cancer repo (vivarium_csu_swissre_cervical_cancer)?

**Comment by yongqx** [comment]
> Is there a reason the cervical cancer validation scripts aren't going in the cervical cancer repo (vivarium_csu_swissre_cervical_cancer)?

In my home directory, i uploaded this file to `vivarium_csu_swissre_cancer`, maybe i should reclone everything if new subfolder was added to the main folder.

**Comment by mattkappel** [comment]
> > Is there a reason the cervical cancer validation scripts aren't going in the cervical cancer repo (vivarium_csu_swissre_cervical_cancer)?
> 
> In my home directory, i uploaded this file to `vivarium_csu_swissre_cancer`, maybe i should reclone everything if new subfolder was added to the main folder.

IMHO, it would be ideal if we had these tests in the repo for the cancer site they target (assuming these aren't generalizable to all the cancer sites). If they are generalizable to all cancer sites, maybe there's a better home for them than the breast cancer repo.

**Comment by yongqx** [comment]
> > > Is there a reason the cervical cancer validation scripts aren't going in the cervical cancer repo (vivarium_csu_swissre_cervical_cancer)?
> > 
> > 
> > In my home directory, i uploaded this file to `vivarium_csu_swissre_cancer`, maybe i should reclone everything if new subfolder was added to the main folder.
> 
> IMHO, it would be ideal if we had these tests in the repo for the cancer site they target (assuming these aren't generalizable to all the cancer sites). If they are generalizable to all cancer sites, maybe there's a better home for them than the breast cancer repo.

I will merge it and move those files to the cervical cancer folder

**Pull request merged**
